

# This file was *autogenerated* from the file generate.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1598 = Integer(1598); _sage_const_2001 = Integer(2001)
R = GF(_sage_const_2 )['x']
for i in range(_sage_const_1598 ,_sage_const_2001 ):
    for p in R.polynomials(i):
        if p.is_irreducible():
                print(i,":",p)
                break

